homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data
  elevation: !secret elevation

  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Denver
  # Platform Customization
  customize: !include_dir_merge_named customize

group: !include_dir_merge_named group

input_boolean: !include_dir_merge_named input_boolean

automation: !include_dir_merge_list automation
script: !include_dir_merge_named script
shell_command:
  cleanup_camera_snapshots: find /config/www/camera_snapshots -type f -name '*.jpg' -mtime +1 -exec rm {} \;

binary_sensor: !include_dir_merge_list binary_sensor

switch: !include_dir_merge_list switch

sensor: !include_dir_merge_list sensor

system_health:

recorder:
  db_url: !secret mysql_url

input_text:
  timestamp:
    name: Filename Timestamp

# shows tracked devices on map
map:

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

logger:
  default: warning
  logs:
    requests.packages.urllib3.connectionpool: critical

# Enables the frontend
frontend:

config:


http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_api_password
  server_port: !secret http_server_port
  base_url : !secret http_url
  ip_ban_enabled: True
  login_attempts_threshold: 5


# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  include:
    domains:
      - light
      - switch
      - lock
      - climate
      - presence
    entities:
      - sensor.thermostat_temperature
      - sensor.motion_sensor_temperature
      - binary_sensor.trig_motion_sensor
      - binary_sensor.trig_front_door_lock
      - binary_sensor.trig_front_door_sensor
      - binary_sensor.trig_guest_window_sensor
      - binary_sensor.trig_master_window_sensor
      - binary_sensor.trig_patio_door_sensor
      - binary_sensor.trig_fire_alarm

# View all events in a logbook
logbook:
  include:
    domains:
      - light
      - switch
      - lock
      - climate
      - presence
      - automation
    entities:
      - sensor.honeywell_th8320zw1000_touchscreen_thermostat_temperature_5_1
      - sensor.linear_wapirz1_temperature_24_1
      - binary_sensor.trig_motion_sensor
      - binary_sensor.trig_front_door_lock
      - binary_sensor.trig_front_door_sensor
      - binary_sensor.trig_guest_sensor
      - binary_sensor.trig_master_sensor
      - binary_sensor.trig_patio_sensor
      - binary_sensor.trig_fire_alarm

# Track the sun
sun:

device_tracker:
  - platform: zyxelc3000z
    url: !secret router_url
    admin_password: !secret router_pass
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False
#  - platform: bluetooth_tracker
#    new_device_defaults:
#      track_new_devices: False
#      hide_if_away: False

apcupsd:
  host: a722577e-apcupsd

notify:
  name: notify_html5
  platform: html5
  vapid_pub_key: !secret vapid_pub_key
  vapid_prv_key: !secret vapid_prv_key
  vapid_email: !secret vapid_email

emulated_hue:
  listen_port: 8300
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: true
  exposed_domains:
    - light
    - switch
    - group
    - input_boolean
#    - media_player
#    - lock

weather:
  - name: Weather
    platform: darksky
    api_key: !secret darksky_api_key

camera:
  - platform: mjpeg
    name: Living Room
    mjpeg_url: !secret lr_camera_url

#Zwave
zwave:
  usb_path: /dev/ttyUSB0
  device_config: !include zwave_device_config.yaml
  network_key: !secret zwave_network_key

zha:
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db

#Todo:
# Freeze Warning Alert
# Power Outage Alert
# Thermostat resume schedule when home.
# In floor heating setback toggle
# Shabbos Mode

# groovy interpretter?
# keypad
# leaksmart
