security_view:
  name: Security
  view: true
  entities:
    - group.security_group
    - group.security_status
    - group.security_config
    - camera.mjpeg_camera

security_group:
  name: Security System
  control: hidden
  entities:
    - input_boolean.security_armed
    - lock.front_door_lock_locked
    - switch.siren_switch
    
security_status:
  name: Sensor Status
  control: hidden
  entities:
    -  binary_sensor.trig_front_door_sensor
    -  binary_sensor.trig_guest_window_sensor
    -  binary_sensor.trig_master_window_sensor
    -  binary_sensor.trig_patio_door_sensor
    -  binary_sensor.trig_motion_sensor
    -  binary_sensor.trig_fire_alarm
    
security_config:
  name: Security Configuration
  entities:
    - automation.lights_alarm
    - automation.siren_alarm
    - input_boolean.security_notifications
    - automation.motion_notifications
    - automation.front_door_notifications
    - automation.guest_window_notifications
    - automation.master_window_notifications
    - automation.patio_door_notifications
    - automation.fire_alarm_notifications